### ISSUE TITLE
How to use it for event listening?

### ISSUE THREAD

**Issue by ytrezq** [jsonrpcx/json-rpc-cxx#15]
I know it s not a bug, but I found the `doc` folder pretty much empty.

How to perform this from the client?

I m having a client interacting with a server through events. That means, that [I send a request to the server which replies Ok to it](https://openethereum.github.io/JSONRPC-parity_pubsub-module#parity_subscribe) and the server sends several others json response for each received events and this is on those events my client need to perform things.

The problem is I m having several different subscriptions, and I need the right function to be called when receiving an event. I m meaning the one matching the subscription.

**Comment by cinemast** [comment]
This is not a pub/sub library. But you can easily build it if you provide a subscribe/unsubscribe remote procedure that takes a callback URL for example.

I did something like that here, but it is completly  unmaintained.

https://github.com/cinemast/libpubsub-cpp
