### ISSUE TITLE
wget or curl command to qury server

### ISSUE THREAD

**Issue by gerald-brandt** [jsonrpcx/json-rpc-cxx#23]
I'd like to see what data is travelling between the http server and client, is there a specific format I can use with wget or curl to query the server from the command line?

The format I'm seeing is this, but I can't translate it to something curl or wget will use.

{"id":1,"jsonrpc":"2.0","method":"mycommand","params":["myargs"]}

**Comment by cinemast** [comment]
There is nothing special related to this lib. The example Http Server can be invoked by this

`curl -d '{"id":1,"jsonrpc":"2.0","method":"AllProducts","params":null}' http://localhost:8484/jsonrpc`
