### ISSUE TITLE
Update doctest

### ISSUE THREAD

**Issue by btuin** [jsonrpcx/json-rpc-cxx#31]
Hi,
`SIGSTKSZ` is no longer a statically defined variable, which makes `doctest` unable to compile.
This change was made by glibc 2.34. (https://sourceware.org/pipermail/libc-alpha/2021-March/123553.html)
`doctest` was updated to fix this issue: https://github.com/doctest/doctest/issues/473
I successfully compiled the project using the latest version of `doctest`.

**Comment by cinemast** [comment]
Thank you for reporting this. I use alpine mostly now which does not use glibc. Which OS release did you currently use to reproduce this?

**Comment by btuin** [comment]
Sorry for the delay, I missed the notification.
I used Arch Linux, but it should be reproducible on any OS with glibc >= 2.34 (latest Ubuntu and Fedora for example).
Thank you for fixing this!
