### ISSUE TITLE
crash with http server and multiple clients

### ISSUE THREAD

**Issue by gerald-brandt** [jsonrpcx/json-rpc-cxx#33]
I consistently crash when I have a single RPC Server using the supplied http server with multiple clients. I fixed it by  adding a mutex in JsonRPCServer::HandleRequest() so it would only handle a single request at a time.

 ```
  std::string HandleRequest(const std::string &requestString) override {
        std::lock_guard<std::mutex> lock (mMutex) ;

      try {
        json request = json::parse(requestString);
        if (request.is_array()) {
          json result = json::array();
          ...
```
 
I don't expect my server to get hit exceptionally hard, so there's no issue for me.

**Comment by cinemast** [comment]
The `HandlRequestMethod` itself is thread safe (no access to global state) and no write access on Dispatcher's maps. So I think this should be about your application logic not being thread safe. If you can share more of your application source maybe we can find the issue. I would be curious.

**Comment by gerald-brandt** [comment]
It's a fairly simple server app, single threaded, sqlite database and json-rpc-cxx using the simple http server provided. When I add multiple clients asking for data, I guarantee a crash unless I add the mutex. Every one of my RPC function/method is wrapped in a mutex (a different one that the one I added into the server file). For example:

method added
`rpcServer.Add("GetHostList", jsonrpccxx::GetHandle(&cRPCServer::GetHostList, *this), {"token"});
`
method
```
deque<string> cRPCServer::GetHostList(string token)
{
    lock_guard<mutex> lock (mMutex) ;

    deque<string> hosts ;

    if(VerifyToken(token))
    {
        hosts = mDatabase->GetHostsLists() ;

    }
    return hosts ;
}

```

**Comment by cinemast** [comment]
This seems to be related to your application itself. SQLite can be configured in single-thread and multi-threaded mode. See [here](https://www.sqlite.org/threadsafe.html). In case `mDatabase` is not configured threadsafe, crashing makes total sense, but this is not at all realted to `HandleRequestMethod` itself.
