### ISSUE TITLE
JsonRpc1Server?

### ISSUE THREAD

**Issue by dtugend** [jsonrpcx/json-rpc-cxx#36]
While working on pull request for issue 35 I noticed I could find no JsonRpc 1 compliant server class, but it says here there is one:
https://github.com/jsonrpcx/json-rpc-cxx/blob/1f8b35881a208e2fad0989292059e47ae45fcddd/README.md?plain=1#L17

https://github.com/jsonrpcx/json-rpc-cxx/blob/1f8b35881a208e2fad0989292059e47ae45fcddd/include/jsonrpccxx/server.hpp#L82-L85

Or is it just me dumbing out?

**Comment by cinemast** [comment]
You are totally right, sorry this was a dumb mistake on my end. If you need JSON-RPC 1.0 I would recommend the other framework: [libjson-rpc-cpp](https://github.com/cinemast/libjson-rpc-cpp)

Sorry for the confusion. I removed the mentioning from the README.
