### ISSUE TITLE
using named parameters in a client invocation

### ISSUE THREAD

**Issue by mfrigerio17** [jsonrpcx/json-rpc-cxx#42]
Hi, there is a check in the dispatcher code that prevents passing named parameters:

`... "invalid parameter: procedure doesn't support named parameter" ..`

Why is that? I suspect it is because the (quite esoteric :)) `createMethodHandle(...`  can only work with a sequence of parameters, is that right?

It is a pity because it prevents writing something very natural like this

```
json args;
args["arg1"] = 1;
args["arg2"] = 33;
client.CallMethod... (... ,args);
```

which was actually possible with libjson-rpc-cpp

**Comment by mfrigerio17** [comment]
I know I can still do it by passing the parameter mapping when adding a method handle, but then the JSON arguments object in the server-side function will not have the same structure (it will be `[1,33]` instead of an object with fields)

**Comment by cinemast** [comment]
Hi! That is what the `NamedParamMapping` is for: https://github.com/jsonrpcx/json-rpc-cxx/blob/master/include/jsonrpccxx/dispatcher.hpp#L20

Do you have a code snippet?

**Comment by mfrigerio17** [comment]
Hello,
sorry I think I formulated badly my original question.

Let's start from this one:

```C++
#include <iostream>
#include <jsonrpccxx/server.hpp>
#include <jsonrpccxx/client.hpp>
#include <jsonrpccxx/inmemoryconnector.hpp>

using json = jsonrpccxx::json;

json aFunction(const json& params) {
    std::cout << "json params: "  << params << std::endl;
    return json(true);
}

int main() {
    jsonrpccxx::JsonRpc2Server rpcServer;
    rpcServer.Add("aFunction", jsonrpccxx::MethodHandle(aFunction), {"arg1", "arg2"});

    InMemoryConnector connector(rpcServer);
    jsonrpccxx::JsonRpcClient client(connector, jsonrpccxx::version::v2);

    json args, ret;
    args["arg1"] = 1.0;
    args["arg2"] = 2.0;
    ret = client.CallMethod<bool>(1, "aFunction", args);

    std::cout << ret << std::endl;
    return 0;
}
```
which fails with a JSON exception:

```
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::type_error'
  what():  [json.exception.type_error.302] type must be array, but is object
```

Probably related: why does [`CallMethod`](https://github.com/jsonrpcx/json-rpc-cxx/blob/master/include/jsonrpccxx/client.hpp#L28) only take a std::vector or std::map of json, and not directly a json object?

**Comment by cinemast** [comment]
Hi!

Something like this should work:

```cpp
json aFunction(const json& args) {
    std::cout << "json params"  << args << std::endl;
    return json(true);
}

int main() {
    jsonrpccxx::JsonRpc2Server rpcServer;
    rpcServer.Add("aFunction", jsonrpccxx::MethodHandle(aFunction), {"arg1", "arg2"});

    InMemoryConnector connector(rpcServer);
    jsonrpccxx::JsonRpcClient client(connector, jsonrpccxx::version::v2);

    jsonrpccxx::named_parameter args;
    json ret;
    args["arg1"] = 1.0;
    args["arg2"] = 2.0;
    ret = client.CallMethod<json>(1, "aFunction", args);

    std::cout << ret << std::endl;
    return 0;
}
```

**Comment by mfrigerio17** [comment]
Hi, thanks for your reply.
I see what you did (btw, it should be `CallMethodNamed`, not `CallMethod`).

However, as I expected it prints:
`json params: [1.0,2.0]`
meaning that the argument was turned into an array (so one cant use the key-value mapping in the method).

Furthermore, and more importantly, I still wont be able to use a json object with named arguments from a different client (maybe written in another language and not using your library).

I suspect implementing true named parameter would be trivial, if one does not use the machinery of `createMethodHandle(` (as I do in my example, where I provide myself the wrapper method using JSON types)

**Comment by cinemast** [comment]
I would go for the JSON types approach then.
